### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by commandline-be** [voondo/redmine_git_server#1]
Thanks for this project, i think it is what i need. Had a look at git_hosting but i felt tears just looking at the stupifying installation procedure.

For git_server I do get errors on SQL tables not existing on install.

**Comment by voondo** [comment]
I don't understand why you have sql errors because there is nothing related to the models in this plugin.
What are the errors ?

**Comment by commandline-be** [comment]
> I don't understand why you have sql errors because there is nothing related to the models in this plugin.
> What are the errors ?

In the meantime i wrote a redmine plugin installation script. will try again.

**Comment by commandline-be** [comment]
The script works much better than me doing it manually, zero SQL errors at the moment. However, after installation of the plugin redmine no longer functions, after uninstall redmine works again.

/opt/hosting/www/redmine/plugins/redmine_contacts/init.rb:29: warning: already initialized constant FCSV
/opt/hosting/www/redmine/plugins/redmine_agile/init.rb:29: warning: previous definition of FCSV was here
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
/opt/hosting/www/redmine/plugins/redmine_contacts/init.rb:29: warning: already initialized constant FCSV
/opt/hosting/www/redmine/plugins/redmine_agile/init.rb:29: warning: previous definition of FCSV was here

**Comment by voondo** [comment]
Theses warnings are not related to this plugin.

Is there any error when redmine no longer functions ?
Did you install `redmine_base_deface` ?

**Comment by commandline-be** [comment]
[ E 2020-06-05 16:27:43.0654 137427/T17 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/hosting/www/redmine: The application encountered the following error:  /opt/hosting/redmine/plugins/redmine_git_server/app/controllers/git_server_controller.rb:34: syntax error, unexpected keyword_rescue, expecting keyword_end
  rescue ActiveRecord::RecordNotFound
        ^ (SyntaxError)
  Error ID: cac63942
  Error details saved to: /tmp/passenger-error-f0TzI4.html

[ E 2020-06-05 16:27:43.0692 137427/T5 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is cac63942. Please see earlier logs for details about the error.

**Comment by commandline-be** [comment]
installation of the plugin no longer breaks redmin after barbarically removing line 34 and 35 in redmine_git_server/app/controllers/git_server_controller.rb

34: rescue ActiveRecord::RecordNotFound
35:     render_404

**Comment by voondo** [comment]
It should be fixed (ruby < 2.5 was not supported)

**Comment by commandline-be** [comment]
Works as expected, thanks for the follow up and fix.

**Comment by ashrafalzyoud** [comment]
> /opt/hosting/www/redmine/plugins/redmine_contacts/init.rb:29: warning: already initialized constant FCSV
> /opt/hosting/www/redmine/plugins/redmine_agile/init.rb:29: warning: previous definition of FCSV was here
> DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
> DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
> DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
> DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
> DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
> DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
> DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /opt/hosting/www/redmine/config/routes.rb:370)
> /opt/hosting/www/redmine/plugins/redmine_contacts/init.rb:29: warning: already initialized constant FCSV
> /opt/hosting/www/redmine/plugins/redmine_agile/init.rb:29: warning: previous definition of FCSV was here

these error in your production log,,, are u solve it??? deprecation error

**Comment by ashrafalzyoud** [comment]
@commandline-be
